name=Camera_IMU_ESPNOW
version=1.0.0
author=User
maintainer=User
sentence=Vision and IMU ESP-NOW library.
paragraph=Sends blob tracking coordinates and IMU motion data via ESP-NOW.
category=Sensors
url=https://github.com
architectures=esp32
includes=Vision.h,IMU.h